# @package _global_

defaults:
  - override /data: ur_robotiq_1cam
  - override /model: fastwam_joint
  - _self_

batch_size: 2
num_workers: 8

model:
  mot_checkpoint_mixed_attn: false
  compile_training_denoise: false

eval_num_inference_steps: 10
mixed_precision: bf16
